version: '2'
services:
    sd1-app:
        image: sd1
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sd1-postgresql:5432/SD1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sd1-postgresql:
        extends:
            file: postgresql.yml
            service: sd1-postgresql
